# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb365572839254d136c99232267160256afec7680d87ca3de96c4872278c0ca0e84cd0f0673eb4e457d842e6c528c1bd47a77e2816db7e4aec09bb37e81b99e

test:
  secret_key_base: 24cb15b16562f2d126ada3baf0f642e0a2db4abf408e7b5c35644e9064123c5c9c1f8f96dfbd22241d82f93ae2caab77b9553fd81b959c9b681aeaed9675cedd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
